# Generated by Django 6.1.1 on 2026-09-15 00:11

import django.core.validators
import django.db.models.deletion
import uuid

import website.models
import website.storage
import website.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Descripción breve"
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Identificador del icono usado por la interfaz.",
                        max_length=80,
                        verbose_name="Icono",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                (
                    "common_problems",
                    models.TextField(
                        blank=True,
                        help_text="Un elemento por línea.",
                        verbose_name="Problemas frecuentes",
                    ),
                ),
                (
                    "process",
                    models.TextField(
                        blank=True,
                        help_text="Describe solo el proceso que pueda confirmarse.",
                        verbose_name="Proceso",
                    ),
                ),
                (
                    "coverage",
                    models.TextField(
                        blank=True,
                        help_text="No publicar zonas hasta confirmarlas.",
                        verbose_name="Cobertura",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        upload_to="website/services/%Y/%m/",
                        validators=[website.validators.validate_image_upload],
                        verbose_name="Imagen",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Visible")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Nombre")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Descripción breve"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Identificador del icono usado por la interfaz.",
                        max_length=80,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Visible")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "categoría de servicio",
                "verbose_name_plural": "categorías de servicio",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(default="CW Reparaciones", max_length=120)),
                ("tagline", models.CharField(blank=True, max_length=180)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[website.validators.validate_phone_number],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[website.validators.validate_phone_number],
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=240, verbose_name="Dirección"),
                ),
                ("city", models.CharField(blank=True, max_length=120, verbose_name="Ciudad")),
                (
                    "region",
                    models.CharField(blank=True, max_length=120, verbose_name="Región"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=120, verbose_name="País"),
                ),
                (
                    "google_maps_url",
                    models.URLField(blank=True, verbose_name="URL de Google Maps"),
                ),
                (
                    "google_business_url",
                    models.URLField(blank=True, verbose_name="URL del perfil de Google"),
                ),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("tiktok", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                (
                    "hours_monday_friday",
                    models.CharField(
                        default="7:00 AM - 5:00 PM",
                        max_length=80,
                        verbose_name="Horario de lunes a viernes",
                    ),
                ),
                (
                    "hours_saturday",
                    models.CharField(
                        default="7:00 AM - 2:00 PM",
                        max_length=80,
                        verbose_name="Horario del sábado",
                    ),
                ),
                (
                    "hours_sunday",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Horario del domingo"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="Se deja vacío hasta confirmar la zona horaria del negocio.",
                        max_length=64,
                        verbose_name="Zona horaria",
                    ),
                ),
                (
                    "feature_services",
                    models.BooleanField(default=True, verbose_name="Servicios"),
                ),
                (
                    "feature_diagnostic_form",
                    models.BooleanField(default=True, verbose_name="Formulario de solicitud"),
                ),
                (
                    "feature_portfolio",
                    models.BooleanField(default=False, verbose_name="Portafolio"),
                ),
                (
                    "feature_reviews",
                    models.BooleanField(default=False, verbose_name="Reseñas"),
                ),
                ("feature_map", models.BooleanField(default=False, verbose_name="Mapa")),
                (
                    "feature_booking",
                    models.BooleanField(default=False, verbose_name="Reservas"),
                ),
                (
                    "feature_tracking",
                    models.BooleanField(default=False, verbose_name="Seguimiento"),
                ),
                (
                    "feature_payments",
                    models.BooleanField(default=False, verbose_name="Pagos"),
                ),
                ("feature_blog", models.BooleanField(default=False, verbose_name="Blog")),
                (
                    "feature_client_portal",
                    models.BooleanField(default=False, verbose_name="Portal de clientes"),
                ),
                ("default_meta_title", models.CharField(blank=True, max_length=180)),
                ("default_meta_description", models.CharField(blank=True, max_length=320)),
                ("google_analytics_id", models.CharField(blank=True, max_length=40)),
                ("meta_pixel_id", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "configuración del sitio",
                "verbose_name_plural": "configuración del sitio",
            },
        ),
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=120, verbose_name="Nombre público"),
                ),
                ("quote", models.TextField(verbose_name="Reseña")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=120, verbose_name="Fuente"),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="URL de la fuente")),
                ("review_date", models.DateField(blank=True, null=True, verbose_name="Fecha")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificada"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publicada"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "reseña de cliente",
                "verbose_name_plural": "reseñas de clientes",
                "ordering": ("order", "-review_date", "pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="website_review_rating_between_1_and_5",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Título")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("equipment", models.CharField(blank=True, max_length=160, verbose_name="Equipo")),
                ("problem", models.TextField(blank=True, verbose_name="Problema")),
                (
                    "work_performed",
                    models.TextField(blank=True, verbose_name="Trabajo realizado"),
                ),
                (
                    "result",
                    models.TextField(blank=True, verbose_name="Resultado verificable"),
                ),
                ("completed_on", models.DateField(blank=True, null=True, verbose_name="Fecha")),
                (
                    "before_image",
                    models.FileField(
                        blank=True,
                        upload_to="website/portfolio/before/%Y/%m/",
                        validators=[website.validators.validate_image_upload],
                        verbose_name="Imagen anterior",
                    ),
                ),
                (
                    "after_image",
                    models.FileField(
                        blank=True,
                        upload_to="website/portfolio/after/%Y/%m/",
                        validators=[website.validators.validate_image_upload],
                        verbose_name="Imagen posterior",
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        upload_to="website/portfolio/media/%Y/%m/",
                        validators=[website.validators.validate_diagnostic_media],
                        verbose_name="Imagen o video adicional",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publicado"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_projects",
                        to="website.service",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "trabajo realizado",
                "verbose_name_plural": "trabajos realizados",
                "ordering": ("order", "-completed_on", "title"),
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=240, verbose_name="Pregunta")),
                ("answer", models.TextField(verbose_name="Respuesta")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Visible")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_items",
                        to="website.service",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "pregunta frecuente",
                "verbose_name_plural": "preguntas frecuentes",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="website.servicecategory",
                verbose_name="Categoría",
            ),
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("equipment", models.CharField(max_length=160, verbose_name="Equipo")),
                ("issue", models.CharField(max_length=160, verbose_name="Problema")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("constant", "Siempre"),
                            ("intermittent", "De forma intermitente"),
                            ("first_time", "Ocurrió una vez"),
                            ("unknown", "No estoy seguro"),
                        ],
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="Descripción"),
                ),
                (
                    "diagnostic_media",
                    models.FileField(
                        blank=True,
                        storage=website.storage.PrivateServiceRequestStorage(),
                        upload_to=website.models.private_request_upload_to,
                        validators=[website.validators.validate_diagnostic_media],
                        verbose_name="Foto o video",
                    ),
                ),
                ("name", models.CharField(max_length=140, verbose_name="Nombre")),
                (
                    "phone",
                    models.CharField(
                        max_length=30,
                        validators=[website.validators.validate_phone_number],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[website.validators.validate_phone_number],
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("phone", "Llamada"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Correo electrónico"),
                        ],
                        default="phone",
                        max_length=20,
                        verbose_name="Preferencia de contacto",
                    ),
                ),
                (
                    "privacy_accepted",
                    models.BooleanField(
                        default=False, verbose_name="Consentimiento de privacidad"
                    ),
                ),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("utm_source", models.CharField(blank=True, max_length=200)),
                ("utm_medium", models.CharField(blank=True, max_length=200)),
                ("utm_campaign", models.CharField(blank=True, max_length=200)),
                ("utm_content", models.CharField(blank=True, max_length=200)),
                ("utm_term", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nueva"),
                            ("in_review", "En revisión"),
                            ("contacted", "Cliente contactado"),
                            ("closed", "Cerrada"),
                            ("archived", "Archivada"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notas internas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="website.service",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud de servicio",
                "verbose_name_plural": "solicitudes de servicio",
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("privacy_accepted", True)),
                        name="website_request_privacy_accepted",
                    )
                ],
            },
        ),
    ]
