# Generated by Django 6.1.1 on 2026-09-15 20:02

import django.db.models.deletion
import uuid
import website.models
import website.storage
import website.validators
from django.db import migrations, models


def unpublish_unverified_legacy_cases(apps, schema_editor):
    PortfolioProject = apps.get_model('website', 'PortfolioProject')
    # Los casos anteriores no tienen constancia de autorización documentada.
    PortfolioProject.objects.filter(is_published=True).update(is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_require_verified_published_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'marca de referencia',
                'verbose_name_plural': 'marcas de referencia',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CoverageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Zona')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('zone_type', models.CharField(choices=[('municipality', 'Municipio'), ('sector', 'Sector'), ('area', 'Área general'), ('to_confirm', 'Zona a consultar')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('is_active', models.BooleanField(default=False, verbose_name='Visible')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'zona de cobertura',
                'verbose_name_plural': 'zonas de cobertura',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('original_video', models.FileField(blank=True, storage=website.storage.PrivateServiceRequestStorage(), upload_to=website.models.portfolio_video_upload_to, verbose_name='Original privado')),
                ('preview_video', models.FileField(blank=True, upload_to='website/portfolio/previews/%Y/%m/', validators=[website.validators.validate_diagnostic_media], verbose_name='Preview web optimizado')),
                ('poster_image', models.FileField(blank=True, upload_to='website/portfolio/posters/%Y/%m/', validators=[website.validators.validate_image_upload], verbose_name='Poster')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('authorization_status', models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_notes', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'video de reparación real',
                'verbose_name_plural': 'videos de reparaciones reales',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported', models.BooleanField(default=False, verbose_name='Atendida')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('authorized_service', models.BooleanField(default=False, verbose_name='Servicio oficial autorizado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'marca asociada a servicio',
                'verbose_name_plural': 'marcas asociadas a servicios',
            },
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='authorization_notes',
            field=models.TextField(blank=True, verbose_name='Notas privadas de autorización'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='authorization_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Autorización de publicación'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Marca comprobada'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Diagnóstico documentado'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='municipality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='sector',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, max_length=240, verbose_name='Dirección particular opcional'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='municipality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha preferida (no confirmada)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora preferida (no confirmada)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='sector',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Número CW'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='data_retention',
            field=models.CharField(blank=True, max_length=160, verbose_name='Plazo de conservación'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='diagnostic_policy',
            field=models.TextField(blank=True, verbose_name='Política de diagnóstico'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='labor_warranty',
            field=models.TextField(blank=True, verbose_name='Garantía de mano de obra'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='NIT o identificación legal'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nombre legal'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_deletion_policy',
            field=models.TextField(blank=True, verbose_name='Eliminación de archivos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='media_retention',
            field=models.CharField(blank=True, max_length=160, verbose_name='Conservación de archivos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='parts_warranty',
            field=models.TextField(blank=True, verbose_name='Garantía de repuestos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo de privacidad'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[website.validators.validate_phone_number], verbose_name='Teléfono alternativo'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Cliente contactado'), ('diagnosis_pending', 'Diagnóstico pendiente'), ('scheduled', 'Programada'), ('in_progress', 'En servicio'), ('waiting_part', 'Esperando repuesto'), ('completed', 'Finalizada'), ('cancelled', 'Cancelada')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='country',
            field=models.CharField(blank=True, default='Colombia', max_length=120, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='charlesrodriguez2009@hotmail.com', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_monday_friday',
            field=models.CharField(blank=True, max_length=80, verbose_name='Horario de lunes a viernes'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_saturday',
            field=models.CharField(blank=True, max_length=80, verbose_name='Horario del sábado'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/cwreparaciones/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='+57 317 504 0053', max_length=30, validators=[website.validators.validate_phone_number], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Servicios Técnicos', max_length=180),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='timezone',
            field=models.CharField(blank=True, default='America/Bogota', max_length=64, verbose_name='Zona horaria'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='+57 317 504 0053', max_length=30, validators=[website.validators.validate_phone_number], verbose_name='WhatsApp'),
        ),
        migrations.RunPython(unpublish_unverified_legacy_cases, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='portfolioproject',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('authorization_status', 'authorized'), _connector='OR'), name='website_portfolio_publication_authorized'),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='website.portfolioproject'),
        ),
        migrations.AddField(
            model_name='servicebrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='website.brand'),
        ),
        migrations.AddField(
            model_name='servicebrand',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_links', to='website.service'),
        ),
        migrations.AddConstraint(
            model_name='portfoliovideo',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('authorization_status', 'authorized'), _connector='OR'), name='website_video_publication_authorized'),
        ),
        migrations.AddConstraint(
            model_name='servicebrand',
            constraint=models.UniqueConstraint(fields=('service', 'brand'), name='website_unique_service_brand'),
        ),
    ]
