# Generated by Django 6.1.1 on 2026-09-15 20:03

import website.models
import website.storage
import website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_brand_coveragezone_portfoliovideo_servicebrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliovideo',
            name='full_video',
            field=models.FileField(blank=True, upload_to=website.models.portfolio_full_upload_to, validators=[website.validators.validate_public_video], verbose_name='Video completo web optimizado'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='original_video',
            field=models.FileField(blank=True, storage=website.storage.PrivateServiceRequestStorage(), upload_to=website.models.portfolio_video_upload_to, validators=[website.validators.validate_private_original_video], verbose_name='Original privado'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='poster_image',
            field=models.FileField(blank=True, upload_to=website.models.portfolio_poster_upload_to, validators=[website.validators.validate_image_upload], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='preview_video',
            field=models.FileField(blank=True, upload_to=website.models.portfolio_preview_upload_to, validators=[website.validators.validate_public_video], verbose_name='Preview web optimizado'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Número CW'),
        ),
    ]
