# Generated by Django 6.1.1 on 2026-09-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_seed_cw_confirmed_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_preference',
            field=models.CharField(choices=[('phone', 'Llamada'), ('whatsapp', 'WhatsApp'), ('email', 'Correo electrónico')], default='whatsapp', max_length=20, verbose_name='Preferencia de contacto'),
        ),
    ]
