# Generated by Django 6.1.1 on 2026-09-19 21:20

import django.db.models.deletion
import uuid
import website.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_securityratelimitbucket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=160, verbose_name='Equipo')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Serie')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'equipo del cliente',
                'verbose_name_plural': 'equipos del cliente',
                'ordering': ('equipment_type', 'brand', 'model'),
            },
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('export_type', models.CharField(default='service_requests', max_length=60)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=8)),
                ('status', models.CharField(choices=[('processing', 'Procesando'), ('ready', 'Disponible'), ('failed', 'Fallida'), ('expired', 'Expirada')], db_index=True, default='processing', max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('relative_path', models.CharField(blank=True, editable=False, max_length=500)),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0, editable=False)),
                ('size_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('error_message', models.CharField(blank=True, editable=False, max_length=500)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'exportación',
                'verbose_name_plural': 'historial de exportaciones',
                'ordering': ('-created_at',),
                'permissions': (('download_exportrecord', 'Puede descargar exportaciones'),),
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('is_closed', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'festivo o excepción',
                'verbose_name_plural': 'festivos y excepciones',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Acceso'), ('correction', 'Corrección'), ('deletion', 'Eliminación')], max_length=16)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('verifying', 'Verificando identidad'), ('processing', 'En proceso'), ('completed', 'Completada'), ('rejected', 'Rechazada')], db_index=True, default='received', max_length=16)),
                ('requester_name', models.CharField(max_length=140)),
                ('requester_contact', models.CharField(max_length=254)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'solicitud de privacidad',
                'verbose_name_plural': 'solicitudes de privacidad',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=255, unique=True)),
                ('destination_url', models.CharField(max_length=500)),
                ('is_permanent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'redirección',
                'verbose_name_plural': 'redirecciones',
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(default='service_requests', max_length=100)),
                ('filters', models.JSONField(default=dict)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'filtro guardado',
                'verbose_name_plural': 'filtros guardados',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Creación'), ('status_changed', 'Cambio de estado'), ('assigned', 'Asignación'), ('note_added', 'Nota agregada'), ('exported', 'Exportación'), ('restored', 'Restauración')], db_index=True, max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'evento de solicitud',
                'verbose_name_plural': 'timeline de solicitudes',
                'ordering': ('-created_at',),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('internal', 'Interna'), ('technical', 'Técnica')], default='internal', max_length=16)),
                ('body', models.TextField(max_length=5000, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'nota de solicitud',
                'verbose_name_plural': 'notas de solicitud',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'secuencia de ticket',
                'verbose_name_plural': 'secuencias de tickets',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrador'), ('technician', 'Técnico'), ('content_manager', 'Gestor de contenido'), ('viewer', 'Solo lectura')], db_index=True, default='viewer', max_length=24)),
                ('phone', models.CharField(blank=True, max_length=30, validators=[website.validators.validate_phone_number])),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('must_change_password', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuarios',
            },
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ('-created_at',), 'permissions': (('assign_servicerequest', 'Puede asignar solicitudes a técnicos'), ('export_servicerequest', 'Puede exportar solicitudes'), ('view_all_servicerequest', 'Puede ver todas las solicitudes'), ('restore_servicerequest', 'Puede restaurar solicitudes de la papelera')), 'verbose_name': 'solicitud de servicio', 'verbose_name_plural': 'solicitudes de servicio'},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizada el'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='En papelera'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visita programada'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technical_notes',
            field=models.TextField(blank=True, verbose_name='Notas técnicas'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Envío a papelera'), ('restore', 'Restauración'), ('export', 'Exportación'), ('login', 'Inicio de sesión'), ('login_failed', 'Inicio de sesión fallido'), ('logout', 'Cierre de sesión'), ('backup', 'Respaldo')], db_index=True, max_length=24)),
                ('object_type', models.CharField(db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'auditoría',
                'ordering': ('-created_at',),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('database', 'Base de datos'), ('media', 'Archivos multimedia'), ('full', 'Completo')], max_length=16)),
                ('status', models.CharField(choices=[('processing', 'Procesando'), ('ready', 'Disponible'), ('failed', 'Fallido')], default='processing', max_length=16)),
                ('relative_path', models.CharField(blank=True, editable=False, max_length=500)),
                ('size_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('error_message', models.CharField(blank=True, editable=False, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'respaldo',
                'verbose_name_plural': 'respaldos',
                'ordering': ('-created_at',),
                'permissions': (('create_backuprecord', 'Puede crear respaldos'), ('restore_backuprecord', 'Puede restaurar respaldos')),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[website.validators.validate_phone_number], verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=30, validators=[website.validators.validate_phone_number], verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('municipality', models.CharField(blank=True, max_length=120, verbose_name='Municipio')),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Dirección')),
                ('normalized_phone', models.CharField(blank=True, db_index=True, editable=False, max_length=80)),
                ('normalized_whatsapp', models.CharField(blank=True, db_index=True, editable=False, max_length=80)),
                ('normalized_email', models.CharField(blank=True, db_index=True, editable=False, max_length=254)),
                ('duplicate_review_required', models.BooleanField(db_index=True, default=False, verbose_name='Revisar posible duplicado')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='En papelera')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('name', 'created_at'),
                'indexes': [models.Index(fields=['is_deleted', 'created_at'], name='website_customer_active')],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='website.customer', verbose_name='Cliente'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'created_at'], name='website_req_status_created'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['assigned_technician', 'status'], name='website_req_tech_status'),
        ),
        migrations.AddField(
            model_name='customerequipment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='website.customer'),
        ),
        migrations.AddField(
            model_name='exportrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests', to='website.customer'),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestevent',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='website.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_request_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestnote',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='website.servicerequest'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cw_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='savedfilter',
            constraint=models.UniqueConstraint(fields=('owner', 'target', 'name'), name='website_unique_saved_filter'),
        ),
    ]
